config/routes.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do |map|   
  get "content/about"

  get "content/contact"

  resources :stores
  resources :products
  
  root :to => "stores#index"

  match '/sitemap', :controller => 'sitemap', :action => :index
  match '/feed', :controller => 'stores', :action => :feed
end

app/controllers/sitemap_controller.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

class SitemapController < ApplicationController
  layout nil

  def index
    headers['Content-Type'] = 'application/xml'
    respond_to do |format|
      format.xml { @stores = Store.all }
    end
  end
end

app/views/sitemap/index.xml.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc><%= root_url %></loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
    <% @stores.each do |store| %>
      <% if store.cafepress_back_design_url %>
        <image:image>
           <image:loc><%= store.cafepress_design_url %></image:loc>
           <image:caption><%= store.description %></image:caption>
           <image:title><%= store.description %></image:title>
        </image:image>
        <image:image>
           <image:loc><%= store.cafepress_back_design_url %></image:loc>
           <image:caption><%= store.description %></image:caption>
           <image:title><%= store.description %></image:title>
        </image:image>
      <% else %>
        <image:image>
           <image:loc><%= store.cafepress_design_url %></image:loc>
           <image:caption><%= store.description %></image:caption>
           <image:title><%= store.description %></image:title>
        </image:image>
      <% end %>
    <% end %>
  </url>
  <url>
    <loc><%= content_about_url %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc><%= content_contact_url %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>