config/routes.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do |map|   
  get "content/about"

  get "content/contact"

  resources :stores
  resources :products
  
  root :to => "stores#index"

  match '/sitemap', :controller => 'sitemap', :action => :index
  match '/feed', :controller => 'stores', :action => :feed
end

app/models/store.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

class Store < ActiveRecord::Base
  validates_uniqueness_of :cafepress_store_id
  has_many :products

  def self.load_cafepress_store(cafepress_store_id)
    store = Store.find_or_create_by_cafepress_store_id(cafepress_store_id)
    cafepress_store_attributes = CafePressAPI.get_store(cafepress_store_id)
    store.description = cafepress_store_attributes[:description]
    store.title = cafepress_store_attributes[:title]
    store.save!
    store
  end

  def self.load_cafepress_store_and_products(cafepress_store_id)
    store = Store.load_cafepress_store(cafepress_store_id)

    store.products.destroy_all

    cafepress_store_products = CafePressAPI.get_store_products(cafepress_store_id)

    cafepress_store_products.each do |cp_product_attributes|
      # pull thumbnails out of hash
      image_urls = cp_product_attributes.delete(:image_urls)

      # pull sizes out of hash
      sizes = cp_product_attributes.delete(:sizes)

      # create product
      product = store.products.build(cp_product_attributes)

      # add thumbnails to product
      image_urls.each do |image_url_attributes|
        product.image_urls.build(image_url_attributes)
      end

      # add sizes to product
      sizes.each do |size_attributes|
        product.sizes.build(size_attributes)
      end
    end

    store.save!
    store

    design_url = CafePressAPI.get_design_url(store.products.first.cafepress_design_id)
    store.update_attributes(:cafepress_design_url => design_url)

    if store.products.first.cafepress_back_design_id
      design_url = CafePressAPI.get_design_url(store.products.first.cafepress_back_design_id)
      store.update_attributes(:cafepress_back_design_url => design_url)
    end
  end

  def mens_products
    products.find_all_by_gender(CafePressAPI::MALE)
  end

  def womens_products
    products.find_all_by_gender(CafePressAPI::FEMALE)
  end

  def unisex_products
    products.find_all_by_gender(CafePressAPI::UNISEX)
  end

  def load_cafepress_data
    Store.load_cafepress_store_and_products(self.cafepress_store_id)
  end

  def self.load_all_stores_cafepress_data
    Store.all.each do |store|
      store.load_cafepress_data
    end
  end
end

app/controllers/stores_controller.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

class StoresController < ApplicationController
  layout 'cafepress_wrapper'
  
  def show
    @store = Store.find(params[:id])
    if params[:product_id]
      @product = Product.find(params[:product_id])
    else
      @product = @store.mens_products.first || @store.womens_products.first || @store.unisex_products.first
    end
    
  end

  def index
    @stores = Store.all(:order => 'updated_at DESC')
  end

  def feed
    @stores = Store.all(:order => 'created_at DESC')
  end
end

app/views/stores/_front_back_image.html.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>

<% if defined?(color_id) && color_id %>
  <div class="front-image" style="display:none;">
    <%= image_tag(product.front_image_url_for_color(params[:color_id]), :alt => '') %>
  </div>
  <div class="back-image" style="display:none;">
    <%= image_tag(product.back_image_url_for_color(params[:color_id]), :alt => '') %>
  </div>
<% else %>
  <div class="front-image" style="display:none;">
    <%= image_tag(product.default_front_image.url, :alt => '') %>
  </div>
  <div class="back-image" style="display:none;">
    <%= image_tag(product.default_back_image.url, :alt => '') %>
  </div>
<% end %>

app/views/stores/_product_details.html.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>

<div id="image">
  <% if product.has_back_design? %>
    <%= render :partial => '/stores/front_back_image', :locals => {:product => product} %>
  <% else %>
    <%= image_tag(product.default_front_image.url, :alt => '') %>
  <% end %>
</div>
<div id="info">
  <%= form_tag(CafePressAPI::ADD_TO_CART_BASE_URL, {:method => :get, :onsubmit => 'return CPW.validate_quantity();'}) do %>
    <%= hidden_field_tag('storeId', 'search') %>
    <%= hidden_field_tag('keepshopping', store_url(product.store, :product_id => product.id)) %>
    <div id="name">
      <%= product.better_default_caption %>&nbsp;&nbsp;<span id="price">$<%= product.price %></span>
    </div>
    <div id="colors">
      <div class="label">
        Color:
      </div>
      <% if product.available_in_multiple_colors? %>
        <div class="multiple_colors">
          <% product.color_ids.each do |color_id| %>
            <% link_to(product_path(product, :color_id => color_id, :id => "color_swatch_#{color_id}"), :remote => true, 'data-color_id' => color_id) do %>
              <%= image_tag(CafePressAPI.lookup_swatch(color_id, product.cafepress_merchandise_id), :alt => '', :class => 'swatch') %>
            <% end %>
          <% end %>
        </div>
        <div id="color_names">
          <% product.color_ids.each do |color_id| %>
            <div class="color_description" id="color_<%=  color_id %>_description" style="display:none;">&nbsp;<%= CafePressAPI::COLORS[color_id][:description] %></div>
          <% end %>
        </div>
      <% else %>
        <% if product.default_front_image.color_id == '0' %>
          <div class="one_color">NO COLOR CHOICES</div>
        <% else %>
          <div class="one_color">ONLY AVAILABLE IN <%= CafePressAPI::COLORS[product.default_front_image.color_id][:description].upcase %></div>
        <% end %>
      <% end %>
      <%= hidden_field_tag("color_#{product.cafepress_product_id}", product.default_color_id, :id => 'selected_color_id') %>
      <div style="clear:both;"></div>
    </div>
    <% if product.has_sizes? %>
      <div id="sizes">
        <div class="label">
          Size:
        </div>
        <div class="size_select">
          <%= select_tag("size_#{product.cafepress_product_id}", options_for_select(product.sizes_array,product.default_cafepress_size_id)) %>
        </div>
        <div style="clear:both;"></div>
      </div>
    <% end %>
    <div id="quantity">
      <div class="label">
        Quantity:
      </div>
      <div>
        <%= text_field_tag("qty_#{product.cafepress_product_id}",'1', :onblur => 'CPW.force_numeric_quantity(this);') %>
      </div>
    </div>
    <div id="more_info">
      <%= link_to('More Product Info at CafePress', product.url, :target => '_cafepress') %>
    </div>
    <div id="add_to_cart">
      <%= submit_tag('Add To Cart') %>
    </div>
  <% end %>
</div>
<div id="loading_image_icon">
  <%= image_tag('ajax-loader.gif') %>
</div>

app/views/stores/index.html.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>

<% content_for :title, Rails.configuration.cpw_title %>
<script type="text/javascript">
  document.observe("dom:loaded", function() {
    setTimeout('CPW.cycle_images();', CPW.cycle_speed);
  });
</script>
<div id="stores">
  <% @stores.each do |store| %>
    <%= link_to store_path(store) do %>
      <div class="store">
        <% if store.cafepress_back_design_url %>
          <div class="front-image" style="background-color:#<%= store.design_background_color %>;">
            <%= image_tag(store.cafepress_design_url, :align => 'middle', :alt => store.description, :title => store.description) %>
          </div>
          <div class="back-image" style="background-color:#<%= store.design_background_color %>;display:none;">
            <%= image_tag(store.cafepress_back_design_url, :align => 'middle', :alt => store.description, :title => store.description) %>
          </div>
        <% else %>
          <div class="image" style="background-color:#<%= store.design_background_color %>;">
            <%= image_tag(store.cafepress_design_url, :align => 'middle', :alt => store.description, :title => store.description) %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="clear"></div>
</div>

app/views/stores/show.html.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>
<% content_for :title, @store.title %>
<script type="text/javascript">          
  document.observe("dom:loaded", function() {
    Event.observe(window,'scroll', function(evt){
      CPW.update_moving_div();
    });

    CPW.bind_color_name_events();
  });

  Event.observe(window, 'load', function() {
    CPW.cycle_speed = 4000;
    CPW.front_images_shown = false;
    setTimeout('CPW.cycle_images();', CPW.cycle_speed);
  });
</script>
<div id="active_product">
  &nbsp;
  <div id="moving_div">
    <%= render :partial => 'product_details', :locals => {:product => @product} %>
  </div>
</div>
<div id="products">
  <table id="mens_and_womens" cellspacing="4px">
    <tr>
      <% if @store.mens_products.length > 0 %>
        <td id="mens">
          <h2>MEN'S</h2>
          <div class="thumbnails">
            <% @store.mens_products.each do |product| %>
              <%= link_to(product_path(product), :remote => true) do %>
                <%= image_tag(product.default_front_thumbnail_url, :alt => '') %>
              <% end %>
            <% end %>
          </div>
        </td>
      <% end %>
      <% if @store.womens_products.length > 0 %>
        <td id="womens">
          <h2>WOMEN'S</h2>
          <div class="thumbnails">
            <% @store.womens_products.each do |product| %>
              <%= link_to(product_path(product), :remote => true) do %>
                <%= image_tag(product.default_front_thumbnail_url, :alt => '') %>
              <% end %>
            <% end %>
          </div>
        </td>
      <% end %>
    </tr>
  </table>

  <% if @store.unisex_products.length > 0 %>
    <div id="unisex">
      <h2>UNISEX</h2>
      <div class="thumbnails">
        <% @store.unisex_products.each do |product| %>
          <%= link_to(product_path(product), :remote => true) do %>
            <%= image_tag(product.default_front_thumbnail_url, :alt => '') %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div style="clear:both;"></div>