config/routes.rb
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do |map|   
  get "content/about"

  get "content/contact"

  resources :stores
  resources :products
  
  root :to => "stores#index"

  match '/sitemap', :controller => 'sitemap', :action => :index
  match '/feed', :controller => 'stores', :action => :feed
end

app/views/layouts/_menu.html.erb
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>

<div class="menu">
  <ul>
    <li class="first"><%= link_to 'Home', root_url %></li>
    <li><%= link_to 'Photos', Rails.configuration.cpw_photos_url, :target => '_photos' %></li>
    <li><%= link_to 'About', content_about_path %></li>
    <li><%= link_to 'Contact', content_contact_path %></li>
    <li><%= link_to 'RSS', '/feed.rss' %></li>
  </ul>
</div>

app/views/layouts/cafepress_wrapper.html.erb
<!DOCTYPE html>
<%
# Copyright 2010-2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePress Wrapper.
# CafePress Wrapper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePress Wrapper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePress Wrapper.  If not, see <http://www.gnu.org/licenses/>.
%>
<html>
<head>
  <title><%= Rails.configuration.cpw_name %> - <%= yield :title %></title>
  <%= stylesheet_link_tag 'cafepress_wrapper', 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'cafepress_wrapper' %>
  <%= csrf_meta_tag %>
  <meta name="description" content="<%= Rails.configuration.cpw_description %>" />
  <link rel="alternate" type="application/rss+xml" title="<%= Rails.configuration.cpw_name %> - <%= yield :title %>" href="/feed.rss" />
  <% if Rails.configuration.cpw_google_analytics %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '<%= Rails.configuration.cpw_google_analytics %>']);
      _gaq.push(['_trackPageview']);
  
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  <% end %>
</head>
<body>
  <div id="header">
    <%= render :partial => 'layouts/menu'%>
  </div>
  <div id="content">
    <div id="cart">
      <%= link_to("#{CafePressAPI::VIEW_CART_BASE_URL}?s=search&keepshopping=#{u(request.url)}") do%>
        <div class="text">Checkout/View Cart</div>
        <div class="image"><%= image_tag('cart.png', :width => '32px', :height => '32px') %></div>
      <% end %>
    </div>
    <%= yield %>
  </div>
  <div id="footer">
    <%= render :partial => 'layouts/menu'%>
  </div>
</body>
</html>